### ISSUE TITLE
Does it support lrc lyrics?

### ISSUE THREAD

**Issue by PMARZV** [alexzhirkevich/KLyrics#1]
Does it support these synced type of lyrics? Example: [Example lrc lyrics](https://www.lyricsify.com/lyrics/jaxomy-agatino-romero-raffaella-carra/pedro/)

**Comment by alexzhirkevich** [comment]
Yes. You need to parse these lines to LyricsLine.Default objects. 

Input format doesn't actually matter. You only need to provide text, line start and line end timestamps.

**Comment by alexzhirkevich** [comment]
But to have wave fade effect you need to provide syllable timestamps for each word
